#include QMK_KEYBOARD_H
#include <keymap_jp.h>
#include "debug.h"
#include "action_layer.h"
#include "version.h"
#include "def.h"
#include "macro.h"

#define BASE  0 // default layer
#define SYMB  1 // symbols
#define NUM   2 // number keys
#define MDIA  3 // media keys
#define DEVEL 4 // programing keys

#define JP_HAT  JP_CIRC  // ^
#define JP_RO   KC_RO    // \, _ 


enum custom_keycodes {
  PLACEHOLDER = SAFE_RANGE, // can always be here
  EPRM,
  VRSN,
  RGB_SLD,
  MC_CM_IN,
  MC_CM_OUT
};

//Tap Dance Declarations
enum {
  TD_COMM_DOT = 0,
  TD_LANG,
  TD_COMMENT,
	TD_P
};

//Tap Dance Definitions
qk_tap_dance_action_t tap_dance_actions[] = {
  [TD_COMM_DOT]  = ACTION_TAP_DANCE_DOUBLE(KC_COMM, KC_DOT),
  [TD_LANG]      = ACTION_TAP_DANCE_DOUBLE(KC_LANG2, KC_LANG1),
  [TD_COMMENT]   = ACTION_TAP_DANCE_FN(dance_comment),
  [TD_P]         = ACTION_TAP_DANCE_FN(dance_p_key)
  //[TD_COMMENT]   = ACTION_TAP_DANCE_DOUBLE(F(MC_CM_IN), F(MC_CM_OUT))
// Other declarations would go here, separated by commas, if you have them
};



const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
// Keymap 0: Basic layer
/*
 * .---------------------------------------------. .---------------------------------------------.
 * |  ESC  |  1  |  2  |  3  |  4  |  5  |JP_LBRC| !JP_RBRC|  6  |  7  |  8  |  9  |  0  |JP_YEN |
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * |  TAB  |  Q  |  W  |  E  |  R  |  T  |JP_HAT | ! MINS  |  Y  |  U  |  I  |  O  |  P  | JP_AT |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * | LCTRL |  A  |  S  |  D  |  F  |  G  |-------! !-------!  H  |  J  |  K  |  L  |JP_CO| SCLN  |
 * !-------+-----+-----+-----x-----x-----!  ESC  ! !TD(TD_C!-----x-----x-----+-----+-----+-------!
 * |MO(DEVE|  Z  |  X  |  C  |  V  |  B  |       | !       |  N  |  M  |COMM | DOT |SLSH | JP_RO |
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  |MO(MDI|LALT |LGUI |RGUI(|RGUI(|                             !MO(NU|LEFT |DOWN | UP  |RIGHT |
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               | LALT  |MO(MDIA| ! RGUI  |MO(MDIA|
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       ! BSPC  !GUI_T(K| LGUI  | !MO(DEVE| RSFT  !  LT   !
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       | LANG2 | !TD(TD_L|       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
// If it accepts an argument (i.e, is a function), it doesn't need KC_.
// Otherwise, it needs KC_*
[BASE] = LAYOUT_ergodox(  // layer 0 : default
        // left hand
        KC_ESC,         KC_1,         KC_2,         KC_3,        KC_4,       KC_5,     JP_LBRC,
        KC_TAB,         KC_Q,         KC_W,         KC_E,        KC_R,       KC_T,     JP_HAT,
        KC_LCTRL,       KC_A,         KC_S,         KC_D,        KC_F,       KC_G,
        MO(SYMB),      KC_Z,         KC_X,         KC_C,        KC_V,       KC_B,     KC_ESC,
        MO(MDIA),       KC_LALT,      KC_LGUI,      RGUI(KC_C),  RGUI(KC_V),
                                                        KC_LALT,        MO(MDIA),
                                                                        KC_LGUI,
                                            KC_BSPC,    GUI_T(KC_SPC),  MO(MDIA),
        // right hand
        JP_RBRC,        KC_6,      KC_7,      KC_8,      KC_9,    KC_0,        JP_YEN,   
        KC_MINS,        KC_Y,      KC_U,      KC_I,      KC_O,    KC_P,        JP_AT,
                        KC_H,      KC_J,      KC_K,      KC_L,    JP_COLN,     KC_SCLN,
        TD(TD_COMM_DOT)/*M(M_C_D)*/,       KC_N,      KC_M,      KC_COMM,   KC_DOT,  KC_SLSH,     JP_RO,
                        MO(DEVEL),   KC_LEFT,   KC_DOWN,   KC_UP  , KC_RIGHT,
        KC_RGUI,        MO(MDIA),
        MO(NUM),
        TD(TD_LANG), RSFT_T(KC_LANG1), LT(SYMB,KC_ENT)
    ),

// Keymap 1: Symbol Layer
/* .---------------------------------------------. .---------------------------------------------.
 * | VRSN  | F1  | F2  | F3  | F4  | F5  |       | !       | F6  | F7  | F8  | F9  | F10 |  F11  |
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * |       |JP_QU|JP_DQ|JP_EX|     |     |       | !       |     |JP_LP|JP_RP|     |JP_PE|  F12  |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |       |JP_AT|JP_SC| DLR |     |     |-------! !-------!JP_HA|JP_LB|JP_RB|     |     |       |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |       |     |     |JP_CO|     |JYEN |       | !       |     |JP_LC|JP_RC|     |     |       |
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  |      |     |     |     |     |                             !     |     |     |     |      |
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               |       |       | !       |       |
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       !       !       |       | !       |       !       !
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       |       | !       |       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
[SYMB] = LAYOUT_ergodox(

       // left hand
       VRSN,      KC_F1,    KC_F2,    KC_F3,    KC_F4,     KC_F5,     KC_TRNS,
       KC_TRNS,   JP_QUOT,  JP_DQT ,  JP_EXLM,  KC_TRNS,   KC_TRNS,   KC_TRNS,
       KC_TRNS,   JP_AT,    JP_SCLN,  KC_DLR,   KC_TRNS,   KC_TRNS,
       KC_TRNS,   KC_TRNS,  KC_TRNS,  JP_COLN,  KC_TRNS,   KC_JYEN,   KC_TRNS,
         KC_TRNS, KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,
                                       KC_TRNS,KC_TRNS,
                                               KC_TRNS,
                               KC_TRNS,KC_TRNS,KC_TRNS,
       // right hand
       KC_TRNS, KC_F6,   KC_F7,     KC_F8,      KC_F9,      KC_F10,  KC_F11,
       KC_TRNS, KC_TRNS, JP_LPRN,   JP_RPRN,    KC_TRNS,    JP_PERC, KC_F12,
                JP_HASH, JP_LBRC,   JP_RBRC,    KC_TRNS,    KC_TRNS, KC_TRNS,
       KC_TRNS, KC_TRNS, JP_LCBR,   JP_RCBR,    KC_TRNS,    KC_TRNS, KC_TRNS,
                         KC_TRNS,   KC_TRNS,    KC_TRNS,    KC_TRNS, KC_TRNS,
       KC_TRNS, KC_TRNS,
       KC_TRNS,
       KC_TRNS, KC_TRNS, KC_TRNS
),

// Keymap 2: Number
/* .---------------------------------------------. .---------------------------------------------.
 * |       |     |     |     |     |     |       | !       |     |     |     |     |     |       |
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * |       |  1  |  2  |  3  |  4  |  5  |       | !       |  6  |  7  |  8  |  9  |  0  |       |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |       |     |     |     |     |     |-------! !-------!     |     |     |     |     |       |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |       |     |     |     |     |     |       | !       |     |     |     |     |     |       |
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  |      |     |     |     |     |                             !     |     |     |     |      |
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               |       |       | !       |       |
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       !       !       |       | !       |       !       !
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       |       | !       |       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
[NUM] = LAYOUT_ergodox(

       // left hand
       KC_TRNS,   KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,
       KC_TRNS,   KC_1,     KC_2,     KC_3,     KC_4,     KC_5,     KC_TRNS,
       KC_TRNS,   KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,
       KC_TRNS,   KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,
         KC_TRNS, KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,
                                       KC_TRNS,KC_TRNS,
                                               KC_TRNS,
                               KC_TRNS,KC_TRNS,KC_TRNS,
       // right hand
       KC_TRNS, KC_TRNS, KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS, KC_TRNS,   
       KC_TRNS, KC_6,    KC_7,      KC_8,      KC_9,       KC_0,    KC_TRNS,   
                KC_TRNS, KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS, KC_TRNS,
       KC_TRNS, KC_TRNS, KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS, KC_TRNS,
                         KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS, KC_TRNS,
       KC_TRNS, KC_TRNS,
       KC_TRNS,
       KC_TRNS, KC_TRNS, KC_TRNS
),
// Keymap 3: Media and mouse keys
/* .---------------------------------------------. .---------------------------------------------.
 * |       |     |     |     |     |     |       | !       |     |     |     |     |     |       |
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * |       |     |     |MS_U |     |     |       | !       |     |     |     |     |     |       |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |       |     |MS_L |MS_D |MS_R |     |-------! !-------!LEFT |DOWN | UP  |RIGHT|     |       |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |       |     |     |     |     |     |       | !       |     |     |     |     |     |       |
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  |      |     |     |BTN1 |BTN2 |                             !     |     |     |     |      |
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               |       |       | !       |       |
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       !       !       |       | !       |       !       !
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       |       | !       |       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
[MDIA] = LAYOUT_ergodox(

       // left hand
       KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
       KC_TRNS, KC_TRNS, KC_TRNS, KC_MS_U, KC_TRNS, KC_TRNS, KC_TRNS,
       KC_TRNS, KC_TRNS, KC_MS_L, KC_MS_D, KC_MS_R, KC_TRNS,
       KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
       KC_TRNS, KC_TRNS, KC_TRNS, KC_BTN1, KC_BTN2,
                                           KC_TRNS, KC_TRNS,
                                                    KC_TRNS,
                                  KC_TRNS, KC_TRNS, KC_TRNS,
       // right hand
       KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS, KC_TRNS,
       KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS, KC_TRNS,
                 KC_LEFT, KC_DOWN, KC_UP  , KC_RIGHT, KC_TRNS, KC_TRNS,
       KC_TRNS,  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS, KC_TRNS,
                          KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS, KC_TRNS,
       KC_TRNS, KC_TRNS,
       KC_TRNS,
       KC_TRNS, KC_TRNS, KC_TRNS
),
// PROGMEM
/* .---------------------------------------------. .---------------------------------------------.
 * |       |     |     |     |     |     |       | !       |     |     |     |     |     |       |
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * |       |     |     |     |     |     |       | !       |     |     |     |     |TD(TD|       |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |       |     |     |     |     |     |-------! !-------!     |     |     |     |     |       |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |       |     |     |TD(TD|     |     |       | !       |     |     |     |     |     |       |
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  |      |     |     |     |     |                             !     |     |     |     |      |
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               |       |       | !       |       |
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       !       !       |       | !       |       !       !
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       |       | !       |       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
[DEVEL] = LAYOUT_ergodox(

       // left hand
       KC_TRNS,   KC_TRNS,  KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,  KC_TRNS,
       KC_TRNS,   KC_TRNS,  KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,  KC_TRNS,
       KC_TRNS,   KC_TRNS,  KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,
       KC_TRNS,   KC_TRNS,  KC_TRNS,   TD(TD_COMMENT),   KC_TRNS,    KC_TRNS,  KC_TRNS,
         KC_TRNS, KC_TRNS,  KC_TRNS,   KC_TRNS,   KC_TRNS,  
                                       KC_TRNS,KC_TRNS,
                                               KC_TRNS,
                               KC_TRNS,KC_TRNS,KC_TRNS,
       // right hand
       KC_TRNS,   KC_TRNS,  KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,  KC_TRNS,   
       KC_TRNS,   KC_TRNS,  KC_TRNS,   KC_TRNS,   KC_TRNS,    TD(TD_P),  KC_TRNS,   
                  KC_TRNS,  KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,  KC_TRNS,
       KC_TRNS,   KC_TRNS,  KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,  KC_TRNS,
                            KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,  KC_TRNS,
       KC_TRNS,   KC_TRNS,
       KC_TRNS,
       KC_TRNS,   KC_TRNS,  KC_TRNS
),
/* template
[] = LAYOUT_ergodox(

       // left hand
       KC_TRNS,   KC_TRNS,  KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,  KC_TRNS,
       KC_TRNS,   KC_TRNS,  KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,  KC_TRNS,
       KC_TRNS,   KC_TRNS,  KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,
       KC_TRNS,   KC_TRNS,  KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,  KC_TRNS,
         KC_TRNS, KC_TRNS,  KC_TRNS,   KC_TRNS,   KC_TRNS,  
                                       KC_TRNS,KC_TRNS,
                                               KC_TRNS,
                               KC_TRNS,KC_TRNS,KC_TRNS,
       // right hand
       KC_TRNS,   KC_TRNS,  KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,  KC_TRNS,   
       KC_TRNS,   KC_TRNS,  KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,  KC_TRNS,   
                  KC_TRNS,  KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,  KC_TRNS,
       KC_TRNS,   KC_TRNS,  KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,  KC_TRNS,
                            KC_TRNS,   KC_TRNS,   KC_TRNS,    KC_TRNS,  KC_TRNS,
       KC_TRNS,   KC_TRNS,
       KC_TRNS,
       KC_TRNS,   KC_TRNS,  KC_TRNS
),
*/
};

const uint16_t PROGMEM fn_actions[] = {
    [1] = ACTION_LAYER_TAP_TOGGLE(SYMB)                // FN1 - Momentary Layer 1 (Symbols)
};

static uint16_t start[100];
const macro_t *action_get_macro(keyrecord_t *record, uint8_t id, uint8_t opt)
{

  uint8_t long_press_id = LP_MCR_START - id;
  if (id >= LP_MCR_START) {
    if (record->event.pressed) {
      // 押下したとき
      start[long_press_id] = timer_read();
      return MACRO_NONE;
    } else {
      return get_press_macro(id, (timer_elapsed(start[long_press_id]) >= MCR_LOMG_PRESS));
    }
  }
  return MACRO_NONE;
};

const macro_t *get_press_macro(uint8_t id, uint8_t isLong) {
	switch(id) {
		case M_C_D :
			if (isLong) return MACRO( T(DOT), END);
			return MACRO( T(COMM), END);
	}
	return MACRO_NONE;
}

bool process_record_user(uint16_t keycode, keyrecord_t *record) {

  switch (keycode) {
    // dynamically generate these.
    case EPRM:
      if (record->event.pressed) {
        eeconfig_init();
      }
      return false;
      break;
    case VRSN:
      if (record->event.pressed) {
        SEND_STRING (QMK_KEYBOARD "/" QMK_KEYMAP " / " QMK_VERSION);
      }
      return false;
      break;
  }
  return true;
}

// Runs just one time when the keyboard initializes.
void matrix_init_user(void) {
#ifdef RGBLIGHT_COLOR_LAYER_0
  rgblight_setrgb(RGBLIGHT_COLOR_LAYER_0);
#endif
};

// Runs constantly in the background, in a loop.
void matrix_scan_user(void) {

};

// Runs whenever there is a layer state change.
uint32_t layer_state_set_user(uint32_t state) {
  ergodox_board_led_off();
  ergodox_right_led_1_off();
  ergodox_right_led_2_off();
  ergodox_right_led_3_off();

  uint8_t layer = biton32(state);
  switch (layer) {
      case 0:
        #ifdef RGBLIGHT_COLOR_LAYER_0
          rgblight_setrgb(RGBLIGHT_COLOR_LAYER_0);
        #else
        #ifdef RGBLIGHT_ENABLE
          rgblight_init();
        #endif
        #endif
        break;
      case 1:
        ergodox_right_led_1_on();
        #ifdef RGBLIGHT_COLOR_LAYER_1
          rgblight_setrgb(RGBLIGHT_COLOR_LAYER_1);
        #endif
        break;
      case 2:
        ergodox_right_led_2_on();
        #ifdef RGBLIGHT_COLOR_LAYER_2
          rgblight_setrgb(RGBLIGHT_COLOR_LAYER_2);
        #endif
        break;
      case 3:
        ergodox_right_led_3_on();
        #ifdef RGBLIGHT_COLOR_LAYER_3
          rgblight_setrgb(RGBLIGHT_COLOR_LAYER_3);
        #endif
        break;
      case 4:
        ergodox_right_led_1_on();
        ergodox_right_led_2_on();
        #ifdef RGBLIGHT_COLOR_LAYER_4
          rgblight_setrgb(RGBLIGHT_COLOR_LAYER_4);
        #endif
        break;
      case 5:
        ergodox_right_led_1_on();
        ergodox_right_led_3_on();
        #ifdef RGBLIGHT_COLOR_LAYER_5
          rgblight_setrgb(RGBLIGHT_COLOR_LAYER_5);
        #endif
        break;
      case 6:
        ergodox_right_led_2_on();
        ergodox_right_led_3_on();
        #ifdef RGBLIGHT_COLOR_LAYER_6
          rgblight_setrgb(RGBLIGHT_COLOR_LAYER_6);
        #endif
        break;
      case 7:
        ergodox_right_led_1_on();
        ergodox_right_led_2_on();
        ergodox_right_led_3_on();
        #ifdef RGBLIGHT_COLOR_LAYER_7
          rgblight_setrgb(RGBLIGHT_COLOR_LAYER_6);
        #endif
        break;
      default:
        break;
    }

  return state;
};
